###

# curl -v
#  -u admin:admin
#  -F file=@/полный/путь/to/data.csv
#  http://localhost:8080/api/data/upload
POST http://localhost:8080/api/data/upload
Authorization: Basic admin admin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data.csv"

< \полный\путь\to\data.csv
--WebAppBoundary--

###

