spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/riskdb
    username: postgres
    password: ruhubo
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.tool.hbm2ddl: ERROR
    org.springframework.web.multipart: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
server:
  port: 8080
